// amctoshsMorpheGraph.js
//
// Pure client-side indexing over AMCTOSHS Morphe's saved, typed data
// ({schemas, instances, traceSchemas, traceInstances, relations} — the
// shape GET /api/amctoshs-morphe returns). Mirrors PDF/amctoshsEntityGraph.js's
// role for the OLD flat AmctoshsEntity model: no DOM/React, fully
// unit-testable, no side effects. Linkage is by real Mongo ObjectId
// (schemaId/sourceSchemaId/traceSchemaId/sourceInstanceId/subjectId/
// objectId), not case-insensitive name matching.
//
// Trace Instances have no domain of their own (that lives on their parent
// Trace Schema — see back/models/AMCTOSHSTraceInstance.js's doc comment)
// so they're domain-bucketed via a join through traceSchemasById.

export const buildMorpheIndex = ({ schemas = [], instances = [], traceSchemas = [], traceInstances = [], relations = [] } = {}) => {
  const byDomain = new Map(); // domain -> { schemas: [], instances: [], traceSchemas: [], traceInstances: [] }
  const ensureDomain = (domain) => {
    if (!byDomain.has(domain)) byDomain.set(domain, { schemas: [], instances: [], traceSchemas: [], traceInstances: [] });
    return byDomain.get(domain);
  };

  const instancesBySchemaId = new Map();       // schemaId -> instance[]
  const traceSchemasBySchemaId = new Map();     // sourceSchemaId -> traceSchema[]
  const traceInstancesByTraceSchemaId = new Map(); // traceSchemaId -> traceInstance[]
  const traceInstancesBySourceInstanceId = new Map(); // sourceInstanceId -> traceInstance[]
  const traceSchemasById = new Map(traceSchemas.map((ts) => [String(ts._id), ts]));

  for (const schema of schemas) {
    ensureDomain(schema.domain).schemas.push(schema);
  }
  for (const instance of instances) {
    ensureDomain(instance.domain).instances.push(instance);
    const key = String(instance.schemaId);
    if (!instancesBySchemaId.has(key)) instancesBySchemaId.set(key, []);
    instancesBySchemaId.get(key).push(instance);
  }
  for (const traceSchema of traceSchemas) {
    ensureDomain(traceSchema.domainOfAccess).traceSchemas.push(traceSchema);
    const key = String(traceSchema.sourceSchemaId);
    if (!traceSchemasBySchemaId.has(key)) traceSchemasBySchemaId.set(key, []);
    traceSchemasBySchemaId.get(key).push(traceSchema);
  }
  for (const traceInstance of traceInstances) {
    const parentDomain = traceSchemasById.get(String(traceInstance.traceSchemaId))?.domainOfAccess;
    if (parentDomain) ensureDomain(parentDomain).traceInstances.push(traceInstance);

    const traceSchemaKey = String(traceInstance.traceSchemaId);
    if (!traceInstancesByTraceSchemaId.has(traceSchemaKey)) traceInstancesByTraceSchemaId.set(traceSchemaKey, []);
    traceInstancesByTraceSchemaId.get(traceSchemaKey).push(traceInstance);

    const sourceInstanceKey = String(traceInstance.sourceInstanceId);
    if (!traceInstancesBySourceInstanceId.has(sourceInstanceKey)) traceInstancesBySourceInstanceId.set(sourceInstanceKey, []);
    traceInstancesBySourceInstanceId.get(sourceInstanceKey).push(traceInstance);
  }

  // relationsByEntityId: entityId (string) -> { outgoing: relation[], incoming: relation[] }
  // "outgoing" = this entity is the subject ("X generates Y"); "incoming" =
  // this entity is the object ("Y is generated by X" — X is what's listed).
  const relationsByEntityId = new Map();
  const ensureEntityBucket = (id) => {
    const key = String(id);
    if (!relationsByEntityId.has(key)) relationsByEntityId.set(key, { outgoing: [], incoming: [] });
    return relationsByEntityId.get(key);
  };
  for (const relation of relations) {
    ensureEntityBucket(relation.subjectId).outgoing.push(relation);
    ensureEntityBucket(relation.objectId).incoming.push(relation);
  }

  const schemaCounts = (schema) => ({
    instanceCount: (instancesBySchemaId.get(String(schema._id)) || []).length,
    traceSchemaCount: (traceSchemasBySchemaId.get(String(schema._id)) || []).length,
  });

  const traceSchemaCounts = (traceSchema) => ({
    traceInstanceCount: (traceInstancesByTraceSchemaId.get(String(traceSchema._id)) || []).length,
  });

  return {
    byDomain,
    instancesBySchemaId,
    traceSchemasBySchemaId,
    traceInstancesByTraceSchemaId,
    traceInstancesBySourceInstanceId,
    relationsByEntityId,
    schemaCounts,
    traceSchemaCounts,
    relationsFor: (id) => relationsByEntityId.get(String(id)) || { outgoing: [], incoming: [] },
  };
};
